### ISSUE TITLE
relative path supported?

### ISSUE THREAD

**Issue by nly** [bungle/lua-resty-fileinfo#1]
I use this library and a little confused about the path. I use relative path it says "cannot open xxx",as I try to use a absolute path it says "ASCII text".

**Comment by bungle** [comment]
Hi, thanks I will look at it.

**Comment by bungle** [comment]
Well, I'm not sure what you mean, maybe you have a problem about what path you are relative to? I tried a few paths and it worked just fine. Can you make a full example?

**Comment by nly** [comment]
![example](http://ww2.sinaimg.cn/large/e8c5b3bfjw1f042adcpmyj20l107d0uu.jpg)

**Comment by bungle** [comment]
Yes, it seems to be relative to nginx binary, and that is by default:

```
/usr/local/openresty/nginx/sbin/
```

**Comment by bungle** [comment]
We can add the `ngx.var.document_root` to it by default if we want. What do you think. One problem about `ngx.var` is that it is not available in all contexts.

**Comment by bungle** [comment]
Or even better relative to file that is executing. But for that you have to use debug-library, and that's not very pretty. As far as I know.

**Comment by bungle** [comment]
Maybe you could just write your own:

``` lua
local function getfullpath(relative)
   -- ...
end
```

**Comment by nly** [comment]
Yes , I use `ngx.var.document_root` as the root_path varible in my project, works well.
